name: Run tests
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Install dependencies
        run: mvn dependency:resolve
      - name: Run tests
        run: mvn test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      enum-file: ${{ steps.publish.output.enum-file-name }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Build Maven project
        run: mvn -B package --file pom.xml -DskipTests
      - name: Publish Enum file name
        id: publish
        run: find target/classes/api/model/Pet*.class -type f -execdir echo 'enum-file-name={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifactory
        uses: actions/upload-artifact@v4
        with:
          name: pom-file
          path: target/classes/api/model
          # path: |
          #   pom.xml
          #   target/classes/api/model
  deployment:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: pom-file
      - name: Output current folder content
        run: ls
      - name: Output stored filename variable
        run: echo ${{ needs.build.outputs.enum-file }}
      - name: Deploy project
        run: echo "Deploying..."