name: PR opening actions
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - develop
    paths-ignore:
      - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        run: echo "Deployment..."