name: PR opening actions
on:
  pull_request:
    type:
      - opened
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        run: echo "Deployment..."