name: Test Project
on: push
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Install dependencies
        run: mvn dependency:resolve
      - name: Run tests
        run: mvn test
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Build Maven project
        run: mvn -B package --file pom.xml -DskipTests
      - name: Deploy project
        uses: echo "Deploying..."

